spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: zhou
    password: 12345
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true